eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30


spring:
  application:
    name: eureka-client-b
  config:
    import: "optional:config-server:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

